[build]
  command = "echo 'Static site ready for deployment'"
  publish = "."
  functions = "netlify/functions"

[dev]
  command = "netlify dev"
  port = 8888
  publish = "."
  autoLaunch = true

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js", "stripe"]


[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"